apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fi2bo4j3l-java-springboot
  janus-idp.io/tekton: fi2bo4j3l-java-springboot
  backstage.io/kubernetes-id: fi2bo4j3l-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fi2bo4j3l-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
